---
base: ../../buildah/0.2/buildah.yaml
removeParams:
  - BUILDER_IMAGE
add:
  - use-source
  - use-cachi2
removeWorkspaces:
  - source
replacements:
  workspaces.source.path: /var/workdir
regexReplacements:
  "/workspace(/.*)": /var/workdir$1
description: |-
    Buildah SAST scanning task
